from fastapi import APIRouter, HTTPException, Depends, Header
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional, List
import io
from datetime import datetime
from app.core.auth import get_current_user, TokenData
from app.core.api_keys import get_api_key_manager

router = APIRouter(prefix="/api/reports", tags=["Reports"])


class ReportRequest(BaseModel):
    scan_id: str
    vulnerabilities: List[dict]
    score: int
    language: str
    format: str = "pdf"


def generate_pdf_report(scan_data: dict) -> bytes:
    """Generate a PDF report from scan data"""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, spaceAfter=30)
    heading_style = ParagraphStyle('Heading', parent=styles['Heading2'], fontSize=14, spaceBefore=20, spaceAfter=10)
    normal_style = styles['Normal']
    
    story = []
    
    story.append(Paragraph("DevGuardian AI - Security Scan Report", title_style))
    story.append(Spacer(1, 20))
    
    # Scan info
    story.append(Paragraph(f"Scan ID: {scan_data.get('scan_id', 'N/A')}", normal_style))
    story.append(Paragraph(f"Date: {scan_data.get('timestamp', datetime.now().isoformat())}", normal_style))
    story.append(Paragraph(f"Language: {scan_data.get('language', 'N/A')}", normal_style))
    story.append(Spacer(1, 20))
    
    # Score
    score = scan_data.get('score', 0)
    score_color = "green" if score >= 80 else "yellow" if score >= 50 else "red"
    story.append(Paragraph(f"Security Score: <font color='{score_color}'><b>{score}/100</b></font>", normal_style))
    story.append(Spacer(1, 20))
    
    # Summary
    total_vulns = scan_data.get('total_vulnerabilities', 0)
    story.append(Paragraph(f"Total Vulnerabilities: {total_vulns}", normal_style))
    story.append(Spacer(1, 20))
    
    # Vulnerabilities table
    if scan_data.get('vulnerabilities'):
        story.append(Paragraph("Vulnerabilities Found", heading_style))
        
        data = [['Severity', 'Type', 'Line', 'Description']]
        for v in scan_data['vulnerabilities']:
            data.append([
                v.get('severity', 'N/A'),
                v.get('vulnerability_type', 'N/A')[:30],
                str(v.get('line_number', 'N/A')),
                v.get('description', 'N/A')[:40]
            ])
        
        table = Table(data, colWidths=[0.8*inch, 1.5*inch, 0.5*inch, 3*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(table)
    
    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph("Generated by DevGuardian AI - https://devguardian.ai", normal_style))
    
    doc.build(story)
    return buffer.getvalue()


def generate_html_report(scan_data: dict) -> str:
    """Generate an HTML report from scan data"""
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>DevGuardian Security Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ color: #1a1a2e; }}
        .score {{ font-size: 48px; font-weight: bold; }}
        .score-good {{ color: #22c55e; }}
        .score-medium {{ color: #eab308; }}
        .score-bad {{ color: #ef4444; }}
        table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background-color: #1a1a2e; color: white; }}
        .critical {{ color: #dc2626; font-weight: bold; }}
        .high {{ color: #ea580c; font-weight: bold; }}
        .medium {{ color: #ca8a04; }}
        .low {{ color: #2563eb; }}
    </style>
</head>
<body>
    <h1>🛡️ DevGuardian AI - Security Report</h1>
    
    <h2>Scan Information</h2>
    <p><strong>Scan ID:</strong> {scan_data.get('scan_id', 'N/A')}</p>
    <p><strong>Date:</strong> {scan_data.get('timestamp', 'N/A')}</p>
    <p><strong>Language:</strong> {scan_data.get('language', 'N/A')}</p>
    
    <h2>Security Score</h2>
    <div class="score {'score-good' if scan_data.get('score', 0) >= 80 else 'score-medium' if scan_data.get('score', 0) >= 50 else 'score-bad'}">
        {scan_data.get('score', 0)}/100
    </div>
    
    <h2>Summary</h2>
    <p>Total Vulnerabilities: <strong>{scan_data.get('total_vulnerabilities', 0)}</strong></p>
    
    <h2>Vulnerabilities</h2>
"""
    
    if scan_data.get('vulnerabilities'):
        html += """
    <table>
        <tr>
            <th>Severity</th>
            <th>Type</th>
            <th>Line</th>
            <th>Description</th>
        </tr>
"""
        for v in scan_data.get('vulnerabilities', []):
            severity = v.get('severity', 'low')
            html += f"""
        <tr>
            <td class="{severity}">{severity.upper()}</td>
            <td>{v.get('vulnerability_type', 'N/A')}</td>
            <td>{v.get('line_number', 'N/A')}</td>
            <td>{v.get('description', 'N/A')}</td>
        </tr>
"""
        html += """
    </table>
"""
    else:
        html += "<p>No vulnerabilities found! 🎉</p>"
    
    html += f"""
    <hr>
    <p><small>Generated by DevGuardian AI - <a href="https://devguardian.ai">https://devguardian.ai</a></small></p>
</body>
</html>
"""
    return html


@router.post("/generate")
async def generate_report(
    request: ReportRequest,
    current_user: TokenData = Depends(get_current_user)
):
    """Generate a scan report in PDF or HTML format"""
    
    scan_data = {
        "scan_id": request.scan_id,
        "vulnerabilities": request.vulnerabilities,
        "score": request.score,
        "language": request.language,
        "timestamp": datetime.now().isoformat(),
        "total_vulnerabilities": len(request.vulnerabilities)
    }
    
    if request.format.lower() == "pdf":
        pdf_bytes = generate_pdf_report(scan_data)
        return StreamingResponse(
            io.BytesIO(pdf_bytes),
            media_type="application/pdf",
            headers={
                "Content-Disposition": f"attachment; filename=scan_report_{request.scan_id}.pdf"
            }
        )
    elif request.format.lower() == "html":
        html = generate_html_report(scan_data)
        return HTMLResponse(content=html)
    else:
        raise HTTPException(status_code=400, detail="Format must be 'pdf' or 'html'")


@router.get("/scan/{scan_id}")
async def get_scan_report(
    scan_id: str,
    format: str = "pdf",
    current_user: TokenData = Depends(get_current_user)
):
    """Get a report for a previous scan"""
    # In a real app, this would fetch from database
    # For now, return a placeholder
    raise HTTPException(status_code=404, detail="Scan not found. Run a new scan to generate a report.")


class HTMLResponse:
    def __init__(self, content: str, status_code: int = 200):
        self.content = content
        self.status_code = status_code
        self.headers = {"Content-Type": "text/html"}
